//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraCuuBMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BieuThue
    {
        public string ID { get; set; }
        public System.DateTime createDate { get; set; }
        public int status { get; set; }
        public string hsCode { get; set; }
        public string description { get; set; }
        public string unit { get; set; }
        public string bieuThue1 { get; set; }
        public double thueSuat { get; set; }
        public string link_file_vn { get; set; }
        public string link_file_en { get; set; }
        public string note { get; set; }
        public string tenBieuThue { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> lastEditDate { get; set; }
        public string lastEditor { get; set; }
    }
}
