//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraCuuBMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQuaPhanTichPhanLoai
    {
        public string ID { get; set; }
        public System.DateTime createDate { get; set; }
        public int status { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> lastEditDate { get; set; }
        public string lastEditor { get; set; }
        public string hsCode { get; set; }
        public string Mota_Dnkhaibao { get; set; }
        public string link_file_vn { get; set; }
        public string link_file_en { get; set; }
        public string unit { get; set; }
        public string Mota_KQPTPL { get; set; }
        public string So_Vanban { get; set; }
        public System.DateTime Ngay_Vanban { get; set; }
        public Nullable<System.DateTime> Ngay_Vanban_HH { get; set; }
        public string CoQuan_PhatHanh_PTPL { get; set; }
        public string CoQuan_TiepNhan_YC_PTPL { get; set; }
        public string DonVi_XNK { get; set; }
        public string ToKhai_HQ { get; set; }
        public string Loai_Hinh { get; set; }
        public string Co_Quan_YC_PTPL { get; set; }
        public string Hieu_Luc_Vanban { get; set; }
        public string description { get; set; }
    }
}
