//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraCuuBMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public string ID { get; set; }
        public string packageName { get; set; }
        public string description { get; set; }
        public System.DateTime createDate { get; set; }
        public int status { get; set; }
        public int type { get; set; }
        public double price { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> lastEditDate { get; set; }
        public string lastEditor { get; set; }
        public int amount { get; set; }
    }
}
