//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraCuuBMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThueVAT
    {
        public string ID { get; set; }
        public int status { get; set; }
        public string mota { get; set; }
        public double value { get; set; }
        public string note { get; set; }
        public string name { get; set; }
    }
}
