//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraCuuBMT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TraCuuBMTEntities : DbContext
    {
        public TraCuuBMTEntities()
            : base("name=TraCuuBMTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<KetQuaPhanTichPhanLoai> KetQuaPhanTichPhanLoais { get; set; }
        public virtual DbSet<ThueVAT> ThueVATs { get; set; }
        public virtual DbSet<BieuThue> BieuThues { get; set; }
    }
}
